name: concept_vector
channels:
 - pytorch
 - huggingface
 - nvidia
 - defaults
dependencies:
  - python=3.11
  - cudatoolkit=11.7.0
  - datasets=2.18.0
  - matplotlib=3.7.1
  - numpy=1.26.4
  - pandas=1.5.3
  - plotly=5.9.0
  - pytorch=2.0.1
  - pip=23.3.1
  - scikit-learn=1.3.0
  - seaborn=0.12.2
  - sentencepiece=0.1.99
  - transformers=4.49.0
  - pip:
    - git+https://github.com/davidbau/baukit@main#egg=baukit
    - bitsandbytes==0.45.3
    - huggingface-hub==0.29.3
    - accelerate==0.29.3