name: concept_vector
channels:
  - pytorch
  - huggingface
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - cudatoolkit=12.4.0
  - datasets=3.6.0
  - matplotlib=3.7.1
  - numpy=2.0.1
  - pandas=2.2.2
  - plotly=5.9.0
  - pytorch=2.4.0
  - pytorch-cuda=12.4
  - pip=23.3.1
  - scikit-learn=1.6.1
  - seaborn=0.12.2
  - sentencepiece=0.1.99
  - transformers=4.51.3
  - pip:
      - git+https://github.com/davidbau/baukit@main#egg=baukit
      - bitsandbytes==0.45.5
      - huggingface-hub==0.31.4
      - accelerate==0.29.3